### ISSUE TITLE
Koodikatselmointi 11.8 by jarmo

### ISSUE THREAD

**Issue by JarmoKallio** [SNurmivaara/Tsoha-Bootstrap#1]
Noniin kurkkailin niin ei mitään outouksia pistänyt silmään; kansiot selkeesti laitettu ja php koodit sisennetty. En saanu vielä sovelluksen linkkii auki, kokeilin sivuja yks kerrallaan. Selkeeltä ja tyylikkään hipsteriltä näyttää :D Tietokannan testidata on myös tyylikäs. Netbeans jotai herjas hello_world_controllerin new() funktiosta, en kyl viel keksiny miksi, joku varattu nimi? Ite en käyttänyt vielä tähän netbeansia ni en tiedä valittaaks se suotta jutuista. 

Dokumentaatiosta selvisi hyvin mistä kyse. Oma tarpeellisten esineiden listaus vaikutti näppärältä. Muuten, en tiedä onko toi sillä drawio:lla tehty kun tossa relaatiotietokantakaaviossa on noit ilmeisesti Tapahtuma- luokan liitytärajoitteita väärässä paikassa. Itel ainaki viimeisimpään pdf:ään ilmesty hassuja artefaktei, nojoo oleellista, tiedän.

Captain obvioukset sikseen. Itse sovelluksen idea kuulostaa hyvältä, etenkin voisin kuvitella että jos on isompi joukko, vaikka yli kymmenen yms lähössä ni alkais varmaan oikeesti tulee ongelmii kyytien ja muun järkkäämisen kanssa. Vaik jotkut kahenkymmenen tyypin leffa/pelimaratonit mökillä jossai korvessa. Toi on hyvä ominaisuus että näkee ajoneuvon tyypin ja kuka kuskina ni sitten tietää vähän, haha, mihin kyytiin uskaltaa. Tai et onko oletettavissa ilmastointia autossa joka vois olla ihan vakavissaanki hyvä tietää että voisi sitten ovelasti taktikoida. Jotkut hc tyypit vois jopa lähtee miettii bensan kulutusta, etenki jos kaikkea ei maksettaiskaan yhteisestä pussista.

Eikai tässä muuta, tsemppiä kurssille, hyvältä näyttää.

Jarmo Kallio

**Comment by SNurmivaara** [comment]
Kiitos palautteesta, tsemppiä myös sulle! :)
